name: Continuous Integration
on:
  push:
    branches:
      - main                    # Will make the workflow run every time you push to any branch
      - hbeard84-exercise-7
jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
    - uses: actions/setup-node@v1
      with:
        dotnet-version: '3.1.405' # SDK Version to use; x will use the latest version of the 3.1 channel
        node-version: '11.13.0'
    - run: dotnet build
    - run: dotnet test
    - run: cd DotnetTemplate.Web && npm i && npm t && npm run lint
  docker-publish:
    needs: build-test
    name: docker-publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: hbeard84/dotnettemplate
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        tags: "${{ github.sha }}"
